In [1]:
l=[[1,1],[2,2],[3,3],[4,4]]

In [2]:
print(l)

[[1, 1], [2, 2], [3, 3], [4, 4]]


In [3]:
import numpy as np

In [11]:
np_arry = np.array(l)
np_arry

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [10]:
type(np_arry)

numpy.ndarray

In [14]:
type(l), type(np_arry)

(list, numpy.ndarray)

In [24]:
lst1=[1,2,3,4]
lst3=[2,3,4,6]
lst4=[6,0,8,7]
merged=np.array([lst1,lst3,lst4])

In [28]:
merged = np.array([lst1,lst3,lst4])

In [29]:
lst1=[1,2,3,4]
lst3=[2,3,4,6]
lst4=[6,0,8,7]


In [32]:
lst1 =[1,2,3,4]
lst2 =[2,3,4,6]
lst3 =[6,0,8,7]

merged = np.array([lst1,lst2,lst3])


In [35]:
ls1 = [1,2,3,4]
ls2 = [3,4,5,5]
ls3 = [0,9,7,8]
merged = np.array ([ls1,ls2,ls3])

In [36]:
merged.shape

(3, 4)

In [37]:
merged[0]

array([1, 2, 3, 4])

In [38]:
merged[0][3]

4

In [40]:
merged[1:]

array([[3, 4, 5, 5],
       [0, 9, 7, 8]])

In [41]:
merged [1:,2:]

array([[5, 5],
       [7, 8]])

In [43]:
np.arrange (0,20)

AttributeError: module 'numpy' has no attribute 'arrange'

In [44]:
np.arrange (1,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [47]:
import numpy as np


AttributeError: module 'numpy' has no attribute 'arrange'

AttributeError: module 'numpy' has no attribute 'arrange'

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
array = np.arrange(0,10)
print(array)


AttributeError: module 'numpy' has no attribute 'arrange'

In [51]:
np.arange(53,70)

array([53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [54]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
np.random.rand(3,3)

array([[0.60482477, 0.99768625, 0.1073278 ],
       [0.9422847 , 0.54961146, 0.36905127],
       [0.6837192 , 0.76143016, 0.63127534]])

In [59]:
n=np.arange(10,20)
n.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])